services:
  TYPO3\CMS\Install\Compatibility\SlotReplacement:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onLanguagePackProcessMirrorUrl'
        event: TYPO3\CMS\Install\Service\Event\ModifyLanguagePackRemoteBaseUrlEvent
